name: Dynamic Programming Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.x'

    - name: Install dependencies
      run: dotnet restore ./DynamicProgramming.sln

    - name: Build
      run: dotnet build ./DynamicProgramming.sln --no-restore

    - name: Run tests
      run: dotnet test ./DynamicProgramming.sln --no-build --verbosity normal

# jobs:
#   super-lint:
#     name: Lint code base
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

       #- name: Run Super-Linter
       # uses: github/super-linter@v4
       # env:
       #   DEFAULT_BRANCH: main
       #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
